SELECT MP.MEMBER_ID, MP.MEMBER_NAME, MP.GENDER, DATE_FORMAT(MP.DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH FROM MEMBER_PROFILE AS MP
WHERE MONTH(MP.DATE_OF_BIRTH) = 3 AND MP.TLNO IS NOT NULL AND MP.GENDER = 'W'
ORDER BY MP.MEMBER_ID;