SELECT B.BOOK_ID, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B
WHERE (B.PUBLISHED_DATE >= '2021-01-01' AND B.PUBLISHED_DATE < '2022-01-01') AND B.CATEGORY = '인문'
ORDER BY B.PUBLISHED_DATE ASC;
